In [1]:
import numpy as np
students = np.array(['Aakash', 'Bikram', 'Dinesh', 'Garima', 'Indira', 'Manisha', 'Nishan', 'Pinky', 'Richa', 'Saroj'])
subjects = np.array(['Physics', 'Chemistry', 'Biology', 'Mathematics', 'English'])

fm = 100  # full mark of each subject
pm = 40  # pass mark of each subject

marks = np.array([[76, 40, 77, 83, 67],
                   [38, 70, 54, 93, 43],
                   [63, 92, 41, 95, 48],
                   [43, 68, 53, 95, 81],
                   [53, 69, 69, 74, 77],
                   [75, 41, 79, 83, 93],
                   [65, 74, 43, 57, 58],
                   [34, 72, 51, 69, 85],
                   [50, 91, 50, 57, 74],
                   [43, 32, 73, 65, 50]])

### Questions
1. Who obtained the highest total marks? <sup><sub>Hint: Use `np.sum()` and `np.argmax()`</sub></sup>
2. Calculate percentage of each student. <sup><sub>Hint: Use `np.sum()`</sub></sup>
2. Find the names of student who failed the exam. <sup><sub>Hint: Use `np.min()` and boolean indexing</sub></sup>
3. How many people failed in Physics? <sup><sub>Hint: Use boolean indexing and `np.count_nonzero()`</sub></sup>
4. Which was the most difficult subject? Assume the subject with least average score to be the most difficult. <sup><sub>Hint: Use `np.mean()` and `np.argmin()`</sub></sup>

#### Question 1 Ans

In [2]:
totalmarks=np.sum(marks,axis=1)

In [3]:
students[np.argmax(totalmarks)]

'Manisha'

#### Question 2 Ans

In [4]:
percentage=totalmarks/5
percentage

array([68.6, 59.6, 67.8, 68. , 68.4, 74.2, 59.4, 62.2, 64.4, 52.6])

#### Question 3 Ans

In [5]:
minmarks=np.min(marks,axis=1)
minmarks

array([40, 38, 41, 43, 53, 41, 43, 34, 50, 32])

In [6]:
students[minmarks<40]

array(['Bikram', 'Pinky', 'Saroj'], dtype='<U7')

#### Question 4 Ans

In [7]:
physicmarks=marks[:,0]
physicmarks

array([76, 38, 63, 43, 53, 75, 65, 34, 50, 43])

In [8]:
physicmarksfail=physicmarks[physicmarks<40]
physicmarksfail

array([38, 34])

In [9]:
np.count_nonzero(physicmarksfail)

2

#### Question 5 Ans

In [10]:
subjectaverage=np.mean(marks,axis=0)

In [11]:
subjects[np.argmin(subjectaverage)]

'Physics'